export enum EQueryKeys {
  CreditRate = "credit-rate",
  CreateCreditRate = "create-credit-rate",
  UserList = "user-list",
  EmployeeList = "employee-list",
  CraeteUser = "create-user",
  CreateEmployee = "create-employee",
  BanUser = "ban-user",
  AccountList = "account-list",
  TransactionHistory = "transaction-history",
  CreditList = "credit-list",
  CreditDetails = "credit-details",
  CreditRating = "credit-rating",
  GetTheme = "get-theme",
}
